"""Curated, versionable Learning Hub curriculum and tutor snippets."""


def _chapter(
	slug, title, summary, level, minutes, tags, topics, objectives, why,
	explanation, concepts, diagram, example, code, steps, mistakes, interviews,
	exercise, quiz, takeaways, references,
):
	return {
		"slug": slug,
		"title": title,
		"summary": summary,
		"level": level,
		"minutes": minutes,
		"tags": tags,
		"topics": topics,
		"objectives": objectives,
		"why": why,
		"explanation": explanation,
		"concepts": concepts,
		"diagram": diagram,
		"example": example,
		"code": code,
		"steps": steps,
		"mistakes": mistakes,
		"interviews": interviews,
		"exercise": exercise,
		"quiz": quiz,
		"takeaways": takeaways,
		"references": references,
	}


CHAPTERS = [
	_chapter(
		"foundations", "AI, ML, Deep Learning and GenAI Foundations",
		"Build a mental model for the technologies behind modern AI products.", "Beginner", 45, ["GenAI", "LLM"],
		["AI vs ML vs deep learning", "Generative AI", "LLMs", "tokens", "context window", "inference", "temperature", "embeddings"],
		["Distinguish AI, ML, deep learning and GenAI", "Describe an LLM request from input to output", "Explain tokens, context and embeddings in plain language"],
		"A clear vocabulary makes later architecture and model choices much easier to reason about.",
		"AI is the broad goal of making machines perform useful tasks. Machine learning learns patterns from examples; deep learning uses layered neural networks. Generative AI uses learned patterns to create new text, images, audio or code. An LLM processes text as tokens, uses its context window as working space, and performs inference to predict an output. Temperature adjusts variation, while embeddings represent meaning as numbers for search.",
		["A token is a text fragment, not always a word", "Context is the material available for one model call", "Inference is a model producing an output", "An embedding is a numeric representation useful for comparing meaning"],
		"Examples + training -> model -> prompt + context -> inference -> generated answer",
		"A support assistant can generate a draft from a question, while a search system can use embeddings to find semantically related help articles.",
		"prompt = \"Explain embeddings to a new learner in two sentences.\"\nanswer = model.invoke(prompt)\nprint(answer)",
		["Identify the task", "Choose a model suited to the task", "Provide input and relevant context", "Evaluate the generated result"],
		["Treating AI, ML and GenAI as synonyms", "Assuming one token equals one word", "Confusing model training with inference"],
		["How do ML and deep learning relate?", "What changes when a prompt exceeds the context window?"],
		"Pick a familiar product and label which part predicts, generates, searches or takes an action.",
		{"question": "Which statement best describes inference?", "choices": ["Training a model from scratch", "Using a trained model to produce an output", "Saving a prompt to a database"], "answer": 1, "explanation": "Inference is the model's response-time computation."},
		["AI is the umbrella term", "LLMs predict continuations from context", "Quality depends on both model and supplied context"],
		[("Google Cloud: Generative AI overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/overview"), ("Google AI for Developers: Gemini API", "https://ai.google.dev/gemini-api/docs")],
	),
	_chapter(
		"transformers", "Large Language Models and Transformers",
		"Understand tokens, embeddings and attention without treating the model as magic.", "Intermediate", 55, ["LLM", "GenAI"],
		["Transformer", "self-attention", "query/key/value", "encoder and decoder", "tokenization", "positional information", "inference"],
		["Explain why attention uses relationships between tokens", "Compare encoder and decoder roles", "Trace a short prompt through a transformer"],
		"A practical understanding of the model helps explain both its strengths and its limits.",
		"A transformer converts tokens into vectors and repeatedly lets each position weigh information from other positions. In self-attention, queries ask what is relevant, keys describe what is available, and values carry the information. Positional signals help preserve order. Encoder-only, decoder-only and encoder-decoder designs are suited to different tasks; chat LLMs commonly generate one token at a time.",
		["Attention is content-dependent mixing", "Tokenization maps text into model units", "Decoder generation is autoregressive", "The architecture learns representations; it does not store a searchable copy of every sentence"],
		"text -> tokens -> embeddings + positions -> attention blocks -> next-token scores -> output tokens",
		"In 'The student opened the bank account', attention can connect 'bank' with 'account'; surrounding tokens disambiguate its meaning.",
		"tokens = tokenizer.encode(\"Attention uses context.\")\nprint(tokens)\nprint(tokenizer.decode(tokens))",
		["Tokenize the input", "Create vector representations", "Mix contextual information with attention", "Predict and decode the next token"],
		["Assuming attention is human-like understanding", "Ignoring tokenization when estimating limits", "Thinking the model sees future generated tokens before producing them"],
		["What do query, key and value represent conceptually?", "Why is decoder generation called autoregressive?"],
		"Draw the input-to-next-token pipeline and annotate where context length applies.",
		{"question": "What does self-attention primarily compute?", "choices": ["A relevance-weighted mix of token information", "A database lookup by exact word", "A permanent memory of the conversation"], "answer": 0, "explanation": "Attention mixes representations according to relationships within the input."},
		["Transformers process contextual token representations", "Attention is a learned relevance mechanism", "Generation is iterative next-token prediction"],
		[("Attention Is All You Need (original paper)", "https://arxiv.org/abs/1706.03762"), ("Google Cloud: Generative AI overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/overview")],
	),
	_chapter(
		"prompt-engineering", "Prompt Engineering",
		"Shape requests with clear roles, examples, constraints and evaluation criteria.", "Beginner", 50, ["LLM", "GenAI"],
		["zero-shot", "few-shot", "role prompting", "structured output", "prompt templates", "evaluation", "reasoning disclosure"],
		["Write an explicit task and output contract", "Choose zero-shot or few-shot prompting", "Evaluate prompts against repeatable examples"],
		"A precise prompt reduces ambiguity, improves consistency and makes failures easier to diagnose.",
		"A prompt is an input specification, not a guaranteed program. State the task, relevant context, constraints and desired output shape. Zero-shot uses instructions alone; few-shot adds examples. For JSON, define the fields and validate the result in code. Ask for concise explanations or a brief rationale; do not rely on exposing hidden chain-of-thought. Test prompts on representative and adversarial examples.",
		["Role: perspective and tone", "Task: the operation to perform", "Context: relevant facts", "Constraints: boundaries and output schema", "Evaluation: examples and measurable checks"],
		"role + task + context + constraints -> model output -> parser/validator -> evaluation",
		"A course-support prompt can require an answer grounded only in an approved lesson excerpt and return {answer, source_ids}.",
		"prompt = f\"Classify this support ticket. Return JSON with category and urgency.\\nTicket: {ticket}\"\nresult = model.invoke(prompt)",
		["Define the task in one sentence", "Add only needed context", "Specify output constraints", "Try normal, edge and unsafe inputs", "Measure quality before changing the prompt"],
		["Adding vague instructions such as 'be smart'", "Assuming valid-looking JSON is schema-valid", "Changing many prompt parts without evaluation"],
		["When are few-shot examples useful?", "How would you test whether a prompt change improved quality?"],
		"Create a zero-shot and few-shot classifier prompt, then compare both on ten fixed examples.",
		{"question": "What makes a prompt change a measurable improvement?", "choices": ["It is longer", "It passes a representative evaluation set more often", "It asks the model to think harder"], "answer": 1, "explanation": "Prompt changes should be judged against repeatable quality criteria."},
		["Prompts are interfaces", "Constrain and validate structured outputs", "Evaluate behavior instead of relying on intuition"],
		[("Google Cloud: Prompt design strategies", "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/prompts/prompt-design-strategies"), ("OpenAI: Prompt engineering", "https://developers.openai.com/api/docs/guides/prompt-engineering")],
	),
	_chapter(
		"llm-apis", "Working with LLM APIs",
		"Connect an application to a model with safe configuration and predictable errors.", "Beginner", 45, ["LLM", "GenAI"],
		["HTTP API", "messages", "environment variables", "timeouts", "retries", "rate limits", "token cost"],
		["Describe a request/response cycle", "Keep credentials server-side", "Handle provider failures and latency"],
		"An API boundary is where application reliability, privacy and operating cost become concrete.",
		"A server sends a model identifier and messages to a provider and receives structured output. Keep the key in server environment configuration, validate user input, set a timeout, and return a stable application response. Retry only transient failures with limits and backoff. Track usage and avoid sending unnecessary history or private data.",
		["System/developer instructions define application behavior", "User messages carry the current task", "HTTP status and JSON body both matter", "Timeouts bound waiting; retries must be finite"],
		"browser -> Flask validation -> provider API -> response validation -> JSON to browser",
		"A Flask route can translate a provider outage into a useful 502 response while logging its traceback on the server.",
		"import os\nfrom langchain_google_genai import ChatGoogleGenerativeAI\n\nllm = ChatGoogleGenerativeAI(\n    model=os.environ[\"GEMINI_MODEL\"],\n    google_api_key=os.environ[\"GOOGLE_API_KEY\"],\n)",
		["Load configuration on the server", "Validate message and history", "Call provider with a timeout", "Validate response content", "Return consistent JSON and log failures safely"],
		["Putting API keys in browser JavaScript", "Retrying invalid requests", "Returning raw provider exception details to users"],
		["Where should provider credentials live?", "Which failures are safe to retry?"],
		"Add a request timeout and safe JSON error response to a toy model endpoint.",
		{"question": "Which is a safe place for an API key?", "choices": ["A public JavaScript file", "A server-side environment variable", "A URL query parameter"], "answer": 1, "explanation": "The browser must never receive provider credentials."},
		["Keep provider calls behind the backend", "Bound latency and retry only transient errors", "Never expose secrets in logs or responses"],
		[("Gemini API: API keys", "https://ai.google.dev/gemini-api/docs/api-key"), ("Google Cloud: Retry strategy", "https://cloud.google.com/storage/docs/retry-strategy")],
	),
	_chapter(
		"embeddings", "Embeddings and Vector Search",
		"Turn semantic similarity into a useful retrieval primitive.", "Intermediate", 55, ["LLM", "RAG"],
		["embedding vectors", "cosine similarity", "vector indexes", "chunking", "metadata", "top-k"],
		["Explain what an embedding represents", "Compare vectors with cosine similarity", "Design a metadata-aware retrieval record"],
		"Embeddings let an application retrieve conceptually related material even when wording differs.",
		"An embedding model maps text into a vector where useful semantic relationships are reflected by geometry. A vector index searches nearby vectors; cosine similarity compares direction while reducing sensitivity to magnitude. Chunking controls the unit of retrieval. Store source, permissions and timestamps as metadata so results can be filtered and cited.",
		["Vectors are model-dependent coordinates", "Similarity is not a truth score", "Top-k controls result volume", "Metadata filters support provenance and access rules"],
		"documents -> chunks -> embedding vectors -> vector index -> query vector -> nearest chunks",
		"A learner asking 'How can I limit model memory?' may retrieve a passage titled 'context window constraints'.",
		"from math import sqrt\n\ndef cosine(a, b):\n    dot = sum(x * y for x, y in zip(a, b))\n    norm_a = sqrt(sum(x * x for x in a))\n    norm_b = sqrt(sum(y * y for y in b))\n    return dot / (norm_a * norm_b)",
		["Split source material into traceable chunks", "Embed each chunk with a chosen model", "Store vectors and metadata", "Embed the query and retrieve filtered neighbors"],
		["Comparing vectors from incompatible embedding models", "Using large chunks that mix unrelated topics", "Treating similarity as proof that a passage answers the question"],
		["Why do retrieval systems keep metadata with vectors?", "What does cosine similarity measure?"],
		"Choose three short passages and explain which metadata fields a learner-facing search should preserve.",
		{"question": "What does top-k usually control?", "choices": ["The number of nearest results returned", "The model temperature", "The vector dimensions"], "answer": 0, "explanation": "Top-k is a retrieval limit, not a model sampling setting."},
		["Embeddings represent text numerically", "Retrieval quality depends on chunking and filters", "Retrieved passages still need relevance checks"],
		[("OpenAI: Embeddings guide", "https://developers.openai.com/api/docs/guides/embeddings"), ("Google Cloud: Vector Search overview", "https://cloud.google.com/vertex-ai/docs/vector-search/overview")],
	),
	_chapter(
		"rag", "Retrieval-Augmented Generation (RAG)",
		"Ground model answers in a small set of relevant, traceable source passages.", "Intermediate", 65, ["RAG", "LLM", "Projects"],
		["ingestion", "chunking", "embedding", "retrieval", "grounded generation", "citations", "evaluation"],
		["Trace the RAG indexing and query paths", "Explain how grounding can reduce unsupported claims", "Build a small document question-answering workflow"],
		"RAG connects a model to information that is private, changing or too large to fit in every prompt.",
		"At ingestion, extract and split documents, attach source metadata, and index embeddings. At question time, retrieve a few relevant chunks, optionally rerank them, then ask the model to answer using only that evidence. Show citations and say when evidence is insufficient. RAG reduces some knowledge failures, but poor retrieval or careless prompts can still produce wrong answers.",
		["Ingestion prepares knowledge", "Retrieval selects evidence for a query", "Generation synthesizes an answer", "Grounding ties claims to source passages"],
		"files -> parse -> chunk + metadata -> embed/index; question -> retrieve -> (rerank) -> prompt with evidence -> answer + citations",
		"A course tutor retrieves the relevant chapter section and cites that section instead of sending all course material to the model.",
		"chunks = retriever.search(question, limit=4)\ncontext = \"\\n\".join(item.text for item in chunks)\nanswer = llm.invoke(make_grounded_prompt(question, context))\nreturn {\"answer\": answer, \"sources\": [item.source for item in chunks]}",
		["Ingest approved documents", "Preserve chunk-to-source links", "Retrieve a small relevant set", "Generate with grounding instructions", "Return citations and evaluate retrieval plus answer quality"],
		["Putting an entire document library in every prompt", "Omitting source identifiers", "Assuming retrieval alone prevents hallucinations"],
		["Why can a RAG answer still hallucinate?", "Which stages should an end-to-end RAG evaluation measure?"],
		"Build a mini RAG flow over three local text files and display the retrieved source names.",
		{"question": "What is the core purpose of retrieval in RAG?", "choices": ["Select relevant evidence for generation", "Train the base model", "Guarantee every answer is correct"], "answer": 0, "explanation": "Retrieval supplies relevant evidence; the whole system still needs evaluation."},
		["Prepare sources before querying", "Retrieve only relevant evidence", "Preserve citations and test failure cases"],
		[("Microsoft Learn: RAG overview", "https://learn.microsoft.com/en-us/azure/search/retrieval-augmented-generation-overview"), ("Google Cloud: RAG overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/rag-overview")],
	),
	_chapter(
		"advanced-rag", "Advanced RAG",
		"Improve retrieval quality with query handling, hybrid ranking and traceability.", "Advanced", 65, ["RAG", "LLM"],
		["hybrid search", "metadata filters", "reranking", "query rewriting", "contextual retrieval", "parent-child chunks", "citations"],
		["Choose a retrieval improvement based on a measured failure", "Explain hybrid ranking and reranking", "Preserve citation and access-control metadata"],
		"Most RAG quality problems begin before generation, in the evidence-selection path.",
		"Hybrid retrieval combines lexical matching with vector similarity. Query rewriting can resolve conversational references; metadata filters restrict the corpus; a reranker reorders candidates more precisely. Parent-child retrieval uses small searchable pieces but returns their larger context. Add citations and evaluate recall, relevance, groundedness and latency. Change one stage at a time against a fixed test set.",
		["Recall: did retrieval find relevant evidence?", "Precision: how much retrieved evidence is useful?", "Reranking: rescore candidates with a stronger relevance signal", "Filters: enforce scope and access"],
		"query -> rewrite + filters -> keyword search + vector search -> merge -> rerank -> cited context -> answer",
		"A support query with a product code benefits from keyword search while a paraphrased concept benefits from vector search.",
		"keyword_hits = keyword_search(query, filters=scope)\nvector_hits = vector_search(embed(query), filters=scope)\ncandidates = reciprocal_rank_fusion(keyword_hits, vector_hits)\nresults = rerank(query, candidates)[:5]",
		["Collect queries that currently fail", "Identify whether failure is recall, ranking or access scope", "Apply one targeted change", "Compare quality, latency and cost"],
		["Adding reranking without measuring its value", "Rewriting away important identifiers", "Applying security filters after retrieval instead of before it"],
		["When is hybrid search preferable to vector-only search?", "How do you evaluate retrieval independently from generation?"],
		"Create five queries with paraphrases and exact IDs; compare lexical and vector retrieval results.",
		{"question": "What is the main job of a reranker?", "choices": ["Reorder retrieved candidates by query relevance", "Create document permissions", "Replace document ingestion"], "answer": 0, "explanation": "A reranker scores a candidate set more carefully."},
		["Diagnose the retrieval failure before adding complexity", "Apply security filters before exposing context", "Measure quality and latency together"],
		[("Microsoft Learn: RAG and hybrid retrieval", "https://learn.microsoft.com/en-us/azure/search/retrieval-augmented-generation-overview"), ("Google Cloud: RAG overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/rag-overview")],
	),
	_chapter(
		"agents", "AI Agents and Agentic AI",
		"Know when a model should choose tools and when a predictable workflow is better.", "Intermediate", 60, ["Agents", "LLM"],
		["chatbot vs workflow vs agent", "tools", "planning", "memory", "state", "loops", "human review", "guardrails"],
		["Distinguish a fixed workflow from an agent", "Describe a bounded tool-use loop", "Add human approval and stop conditions"],
		"The word agent can hide very different levels of autonomy, risk and operating cost.",
		"A chatbot mainly responds; a workflow follows developer-defined steps; an agent can choose among tools and steps based on observations. A reliable agent needs a narrow goal, documented tools, permission checks, bounded iterations and a clear stop condition. Keep people in the loop for sensitive or irreversible actions. Prefer a simpler workflow unless flexibility demonstrably helps.",
		["Tools are explicit capabilities", "State records task progress", "Observations are tool results", "Guardrails constrain allowed behavior", "Human approval is a control point"],
		"goal -> model chooses allowed tool -> permission check -> tool result -> next decision -> stop or ask a person",
		"A study planner may search approved lessons and draft a schedule; it should ask before changing a learner's calendar.",
		"for step in range(max_steps):\n    action = planner.choose(goal, state, allowed_tools)\n    if action.name == \"finish\":\n        break\n    result = execute_with_permission_check(action)\n    state.append({\"action\": action.name, \"result\": result})",
		["Define success and permitted actions", "Expose the smallest useful tool set", "Check authorization before execution", "Record outcomes and stop at a bound"],
		["Giving tools broad permissions", "Using an unbounded loop", "Calling a fixed workflow an agent without model-directed choices"],
		["How does an agent differ from a deterministic workflow?", "What actions need human confirmation?"],
		"Design a read-only lesson finder agent and list three actions it must never take.",
		{"question": "When should a team prefer a simple workflow?", "choices": ["When the task has predictable steps", "Whenever a model is involved", "Never; agents are always better"], "answer": 0, "explanation": "Fixed workflows are often more predictable and cheaper for known tasks."},
		["Choose autonomy deliberately", "Bound tools and loops", "Use approval for consequential actions"],
		[("Anthropic: Building effective agents", "https://www.anthropic.com/research/building-effective-agents"), ("Google Cloud: Agents overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/agents/overview")],
	),
	_chapter(
		"agent-architecture", "Agent Architecture and Multi-Agent Systems",
		"Compare single-agent, planner/executor and supervisor patterns with their trade-offs.", "Advanced", 60, ["Agents"],
		["single agent", "supervisor", "planner/executor", "specialists", "communication", "orchestration", "complexity"],
		["Sketch common agent topologies", "Choose boundaries for specialist tasks", "Recognize when multi-agent designs are unnecessary"],
		"More agents add coordination, latency and failure modes; architecture should follow measurable needs.",
		"A single agent is easiest to observe. Planner/executor separates task decomposition from controlled actions. A supervisor routes work to specialists and combines results. Multi-agent systems help when subtasks are genuinely distinct and can be evaluated independently; otherwise a single prompt or fixed workflow is simpler. Define message schemas, ownership, budgets and failure recovery between components.",
		["Supervisor owns routing", "Specialists have narrow responsibilities", "Shared state needs explicit schemas", "Coordination overhead can exceed task value"],
		"request -> supervisor -> specialist A / specialist B -> validated results -> supervisor response",
		"A curriculum assistant could route a lesson question to a teaching specialist and a code bug to a code reviewer, then validate the combined response.",
		"def route(task):\n    if task.kind == \"lesson\":\n        return lesson_worker(task)\n    if task.kind == \"code_review\":\n        return code_worker(task)\n    return general_workflow(task)",
		["Measure the single-system baseline", "Separate only tasks with distinct tools or quality criteria", "Specify inter-agent inputs and outputs", "Test partial failure and conflicting results"],
		["Using many agents as a status symbol", "Passing unbounded conversation history between workers", "Failing to validate delegated results"],
		["What does a supervisor add?", "How would you know a multi-agent design is worth its cost?"],
		"Draw a two-specialist system and mark the data each worker is allowed to receive.",
		{"question": "What is a sound reason to add a specialist agent?", "choices": ["A distinct task needs its own tools or evaluation", "The diagram looks more advanced", "To avoid validating outputs"], "answer": 0, "explanation": "Specialists are useful when responsibilities and quality criteria differ."},
		["Start with a baseline", "Keep delegation narrow and typed", "Measure coordination cost and partial failures"],
		[("Anthropic: Building effective agents", "https://www.anthropic.com/research/building-effective-agents"), ("Microsoft Learn: Agent design patterns", "https://learn.microsoft.com/en-us/azure/architecture/ai-ml/guide/ai-agent-design-patterns")],
	),
	_chapter(
		"mcp-tools", "MCP, Tools and External Systems",
		"Understand a standard interface for connecting AI applications to tools and resources.", "Advanced", 55, ["MCP", "Agents"],
		["MCP clients and servers", "tools", "resources", "prompts", "external systems", "consent", "security"],
		["Describe MCP's client/server relationship", "Distinguish tools, resources and prompts", "Identify consent and security boundaries"],
		"Standardized integrations can reduce one-off glue code, but they still need careful authorization.",
		"Model Context Protocol standardizes how an AI host can discover and use capabilities exposed by servers. Tools perform actions, resources expose data, and prompts can provide reusable templates. MCP does not automatically make a tool safe: authenticate connections, review requested scopes, validate arguments and results, and require approval for consequential writes.",
		["Host contains the user-facing AI application", "Client manages a server connection", "Server exposes declared capabilities", "Consent and authorization remain application responsibilities"],
		"AI host -> MCP client <-> MCP server -> approved tool/resource -> external system",
		"A read-only class-notes server may expose a search tool and note resources; saving a note would require a separate authorized write.",
		"tool = {\n    \"name\": \"search_lessons\",\n    \"description\": \"Search published lesson titles\",\n    \"inputSchema\": {\"type\": \"object\", \"properties\": {\"query\": {\"type\": \"string\"}}}\n}",
		["List the capabilities a client discovers", "Check user identity and authorization", "Validate every tool argument", "Return bounded results with provenance"],
		["Assuming protocol support equals permission", "Exposing broad filesystem or database access", "Trusting tool output as instructions"],
		["What is the difference between a tool and a resource?", "Where should approval occur for a write action?"],
		"Specify a read-only lesson-search tool with a narrow schema and a maximum result count.",
		{"question": "Does MCP itself authorize every requested action?", "choices": ["Yes, protocol use means permission", "No, hosts and servers still enforce consent and access controls", "Only for read operations"], "answer": 1, "explanation": "Protocol interoperability does not replace authorization."},
		["MCP standardizes capability connections", "Tools and resources are distinct", "Authorization and validation remain essential"],
		[("Model Context Protocol: Introduction", "https://modelcontextprotocol.io/introduction"), ("MCP: Security best practices", "https://modelcontextprotocol.io/docs/tutorials/security/security_best_practices")],
	),
	_chapter(
		"memory-context", "AI Memory and Context Engineering",
		"Select, summarize and protect the information supplied to each model call.", "Advanced", 55, ["LLM", "Agents"],
		["short-term memory", "long-term memory", "conversation history", "retrieval memory", "context window", "context engineering"],
		["Distinguish context from persistent memory", "Build a bounded history policy", "Select context by relevance and permissions"],
		"The context supplied to a model is an engineered resource with limits, cost and privacy implications.",
		"Context is what a model sees for one call; memory is application-managed information that may survive calls. Short-term conversation state can be summarized or trimmed. Long-term memory should be explicit, useful, consent-aware and retrievable. Context engineering selects instructions, current task, relevant evidence and history rather than dumping everything into the window.",
		["Working context is finite", "Memory requires storage and retrieval policies", "Summaries are lossy and should preserve decisions", "Permission checks apply before retrieval"],
		"history + current task -> relevance/permission filter -> compact context -> model -> validated memory update",
		"A tutor can retain the learner's chosen difficulty setting but should not silently preserve sensitive personal details.",
		"recent = history[-6:]\nsummary = summarize_older_turns(history[:-6])\ncontext = build_context(summary, recent, retrieved_lesson)",
		["Choose what must persist", "Set retention and deletion rules", "Retrieve only what is relevant and authorized", "Keep recent turns and summarize older ones"],
		["Sending the whole transcript forever", "Treating a model's generated summary as authoritative state", "Saving sensitive facts without purpose or consent"],
		["How is context different from persistent memory?", "What should a safe memory deletion feature remove?"],
		"Write a policy for a tutor's short-term and long-term memory, including deletion behavior.",
		{"question": "What is context engineering?", "choices": ["Selecting and organizing useful input for a model call", "Increasing the model's parameter count", "Saving every conversation permanently"], "answer": 0, "explanation": "It is the deliberate construction of a useful, bounded context."},
		["Select context instead of dumping it", "Memory is an application decision", "Protect, minimize and make stored memory controllable"],
		[("Anthropic: Effective context engineering for AI agents", "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"), ("Google Cloud: Generative AI overview", "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/overview")],
	),
	_chapter(
		"multimodal", "Multimodal Generative AI",
		"Work with models that interpret or generate more than text.", "Intermediate", 50, ["GenAI", "LLM"],
		["text", "images", "audio", "video", "documents", "vision models", "modalities"],
		["Identify common modalities and tasks", "Design an input pipeline for mixed media", "Account for privacy and uncertainty in media outputs"],
		"Many useful learning and accessibility tasks require understanding diagrams, speech or documents as well as text.",
		"Multimodal models map different input types into representations that can be processed together or through specialized encoders. Applications may transcribe audio, summarize a document, describe an image or answer questions about a clip. Preprocess safely, respect size and format limits, cite source regions when possible, and ask for human review when interpretation is uncertain.",
		["Modality is an information type", "Preprocessing can affect quality", "Models can miss details or infer incorrectly", "Media may contain private information"],
		"image/audio/document -> validate + preprocess -> multimodal model -> grounded text or generated media -> review",
		"A learner uploads a chart and asks for a plain-language description; the answer should distinguish visible labels from inferred meaning.",
		"response = model.generate_content([\n    \"Describe the visible trend; do not infer missing values.\",\n    image_part,\n])\nprint(response.text)",
		["Validate media type and size", "Remove unnecessary metadata", "Provide a precise task", "Review output and cite the relevant media when supported"],
		["Assuming image descriptions are always accurate", "Uploading confidential media without consent", "Using an output without checking transcription or OCR errors"],
		["Why can OCR or transcription errors affect downstream answers?", "What review step would you add for an image-based grade decision?"],
		"Create an accessibility workflow for a lecture clip and identify a human verification point.",
		{"question": "What should an application do before processing uploaded media?", "choices": ["Validate type, size and authorization", "Trust all embedded instructions", "Store it forever"], "answer": 0, "explanation": "Input validation and privacy checks come before model processing."},
		["Multimodal inputs need validation", "Model outputs can be uncertain", "Privacy and review are part of the pipeline"],
		[("Gemini API: Image understanding", "https://ai.google.dev/gemini-api/docs/image-understanding"), ("Gemini API: Audio understanding", "https://ai.google.dev/gemini-api/docs/audio")],
	),
	_chapter(
		"evaluation-safety", "Evaluation, Safety and Guardrails",
		"Test quality and constrain failure modes before deployment.", "Advanced", 60, ["GenAI", "Agents"],
		["hallucination", "prompt injection", "data leakage", "grounding", "evaluation datasets", "quality metrics", "human review"],
		["Build a small evaluation set", "Separate quality checks from safety controls", "Identify prompt injection and data exposure risks"],
		"A compelling demo is not evidence that an AI feature is reliable, safe or fair.",
		"Create representative test cases with expected properties, not just one ideal answer. Measure task success, groundedness, citation support, refusal behavior, latency and cost. Treat retrieved documents and user text as untrusted data. Enforce access in code, minimize sensitive context, log safely and route high-impact decisions to a human.",
		["Hallucination: unsupported generated claims", "Prompt injection: untrusted content tries to change behavior", "Guardrail: enforceable boundary in system or code", "Evaluation: repeatable evidence about quality"],
		"test set -> model + retrieval -> quality/safety checks -> release threshold -> monitor and review",
		"A tutor should not reveal another learner's notes even if a prompt or retrieved text requests it; the database query must enforce ownership.",
		"for case in evaluation_cases:\n    result = assistant.answer(case.input)\n    assert result.has_supported_citations\n    assert not exposes_private_data(result)\n    record_metrics(case.id, result)",
		["Write normal and adversarial cases", "Check access control outside the model", "Measure response quality and failure rates", "Review incidents and update tests"],
		["Relying on a system prompt as the only security control", "Evaluating only happy paths", "Logging private prompts or credentials"],
		["How would you test groundedness?", "Why must authorization be enforced outside the model?"],
		"Draft five prompt-injection test cases for a document tutor and the expected safe behavior.",
		{"question": "Which is the strongest access-control boundary?", "choices": ["A prompt telling the model not to show private data", "A server-side ownership check before retrieval", "A UI label saying private"], "answer": 1, "explanation": "Authorization belongs in application logic, not only model instructions."},
		["Test representative failures", "Enforce permissions in code", "Monitor quality, safety, privacy and cost"],
		[("OWASP: Top 10 for LLM Applications", "https://owasp.org/www-project-top-10-for-large-language-model-applications/"), ("NIST: AI Risk Management Framework", "https://www.nist.gov/itl/ai-risk-management-framework")],
	),
	_chapter(
		"production", "Production GenAI Systems",
		"Design for reliable operations: latency, cost, monitoring and controlled access.", "Advanced", 55, ["GenAI", "LLM"],
		["architecture", "caching", "latency", "cost", "logging", "monitoring", "security", "rate limits", "deployment"],
		["Trace a production request", "Identify cost and latency controls", "Plan monitoring and incident response"],
		"Production readiness is a system property, not a model setting.",
		"A production request passes through authentication, validation, retrieval, a provider call and response checks. Bound every stage with timeouts, rate limits and input caps. Cache only safe, repeatable results. Monitor latency, provider errors, token use and answer quality without logging secrets. Have a fallback message and a process for provider outages.",
		["Latency budgets divide time across stages", "Caching needs a privacy-aware key", "Observability records useful, minimal signals", "Rate limits protect service and cost"],
		"client -> auth/rate limit -> context retrieval -> model timeout -> response validation -> metrics + safe output",
		"A repeated public course-catalog answer may be cached; a private student-specific answer must be keyed and isolated by authorization scope.",
		"cache_key = hash((normalized_question, permission_scope, model_version))\nif cache_key in cache:\n    return cache[cache_key]\nreturn call_model_with_timeout(question)",
		["Set latency and cost budgets", "Instrument each backend stage", "Enforce identity and rate limits", "Test provider outage and malformed output paths"],
		["Caching private answers across users", "Logging API keys or sensitive student records", "Retrying provider errors without a deadline"],
		["Which metrics help distinguish retrieval latency from provider latency?", "What must be part of a safe AI cache key?"],
		"Create an outage checklist for an LLM call that times out or returns a provider error.",
		{"question": "What is a safe caching rule for private answers?", "choices": ["Cache by question alone", "Include authorization scope or avoid caching", "Share all user responses"], "answer": 1, "explanation": "A cache must not cross permission boundaries."},
		["Budget time and tokens", "Secure the full request path", "Test failure and recovery behavior"],
		[("Google Cloud: Generative AI best practices", "https://cloud.google.com/vertex-ai/generative-ai/docs/learn/best-practices"), ("Google Cloud: Cloud logging security", "https://cloud.google.com/logging/docs/audit/best-practices")],
	),
	_chapter(
		"capstone", "Capstone: AI Tutor and Knowledge Assistant",
		"Bring ingestion, retrieval, tutoring, history, citations and evaluation together.", "Advanced", 120, ["Projects", "RAG", "Agents"],
		["Flask backend", "LLM API", "document ingestion", "vector retrieval", "citations", "conversation history", "evaluation", "deployment"],
		["Plan an end-to-end tutor architecture", "Deliver grounded answers with sources", "Define test, safety and deployment checks"],
		"A complete vertical slice demonstrates how model behavior depends on product and system design.",
		"Build a small tutor over a curated set of learning notes. A web client sends a question and selected chapter to a Flask API. The backend checks identity, retrieves a few permitted passages, calls the existing model service, validates the reply and returns answer plus citations. Store bounded conversation state and chapter progress separately. Add evaluation and failure telemetry before deployment.",
		["Frontend owns interaction state", "Backend owns secrets and authorization", "Retrieval owns evidence selection", "Evaluation checks both answer and sources"],
		"learner UI -> Flask auth/API -> selective retrieval -> LangChain model call -> answer + citations -> history/progress",
		"A learner asks 'explain attention simply'; the tutor retrieves one approved lesson section and cites the chapter title.",
		"passages = retrieve(question, chapter_id, owner_id, limit=3)\nanswer = tutor.ask(question, context=passages, history=recent_turns)\nreturn {\"answer\": answer, \"citations\": [p.source for p in passages]}",
		["Select a small, permitted source collection", "Build ingestion and retrieval", "Connect the existing model service", "Render citations and bounded history", "Test privacy, quality, latency and provider failures"],
		["Sending every chapter on every request", "Trusting client-supplied ownership", "Shipping without end-to-end tests or citations"],
		["Where should the provider key live?", "How do you prevent a note from leaking across learners?"],
		"Build a local tutor that answers one chapter question with one visible source and one automated evaluation case.",
		{"question": "Which component should enforce learner data ownership?", "choices": ["The model prompt", "The Flask backend and database", "The browser only"], "answer": 1, "explanation": "The trusted backend must enforce authorization before retrieving private data."},
		["Keep provider secrets server-side", "Retrieve only relevant authorized material", "Test the complete path including errors"],
		[("Microsoft Learn: RAG overview", "https://learn.microsoft.com/en-us/azure/search/retrieval-augmented-generation-overview"), ("Anthropic: Building effective agents", "https://www.anthropic.com/research/building-effective-agents"), ("Model Context Protocol: Introduction", "https://modelcontextprotocol.io/introduction")],
	),
]


PRACTICE_LABS = [
	{"slug": "prompt-playground", "title": "Prompt Engineering Playground", "objective": "Compare prompt patterns on a fixed task.", "level": "Beginner", "architecture": "input cases -> prompt variants -> rubric -> comparison", "steps": ["Choose a small classification task", "Write zero-shot and few-shot prompts", "Score outputs against a fixed rubric"], "challenge": "Add ambiguous examples and track where outputs change."},
	{"slug": "llm-api-chatbot", "title": "LLM API Chatbot", "objective": "Build a server-mediated chat request with safe configuration.", "level": "Beginner", "architecture": "browser -> Flask -> model API -> JSON reply", "steps": ["Add a server route", "Load the key from environment", "Validate input and handle timeout"], "challenge": "Add a bounded conversation history."},
	{"slug": "embedding-search", "title": "Embedding Search", "objective": "Retrieve the most relevant paragraph by meaning.", "level": "Intermediate", "architecture": "paragraphs -> embeddings -> nearest neighbors -> results", "steps": ["Prepare five paragraphs", "Create embeddings", "Compare query similarity"], "challenge": "Add source metadata and a category filter."},
	{"slug": "mini-rag", "title": "Mini RAG Assistant", "objective": "Ground one answer in a small local knowledge set.", "level": "Intermediate", "architecture": "documents -> chunks -> retrieve -> answer + citations", "steps": ["Split three documents", "Retrieve a small context", "Return source titles with the answer"], "challenge": "Test a question with no supporting passage."},
	{"slug": "document-qa", "title": "Document Q&A", "objective": "Answer questions from a document with visible provenance.", "level": "Intermediate", "architecture": "upload -> validate -> parse -> retrieve -> cite", "steps": ["Restrict file types and size", "Extract text and page metadata", "Render citations"], "challenge": "Compare retrieval on tables and headings."},
	{"slug": "ai-tutor", "title": "AI Tutor", "objective": "Teach a learner using chapter context and a short quiz.", "level": "Intermediate", "architecture": "chapter -> learner question -> selective context -> tutor", "steps": ["Choose one chapter", "Add explain-simply and quiz actions", "Keep history bounded"], "challenge": "Track learner completion without storing unnecessary personal data."},
	{"slug": "tool-calling", "title": "Tool-Calling Agent", "objective": "Let a model request one narrow, read-only tool.", "level": "Advanced", "architecture": "model request -> schema validation -> tool -> result", "steps": ["Define a narrow tool schema", "Validate and authorize arguments", "Return bounded results"], "challenge": "Add explicit approval before any write."},
	{"slug": "agentic-workflow", "title": "Agentic Workflow", "objective": "Compose bounded steps with a clear finish condition.", "level": "Advanced", "architecture": "plan -> execute -> observe -> verify -> stop", "steps": ["Define task success", "Add a maximum-step limit", "Test tool failure"], "challenge": "Compare the workflow to a single model call."},
	{"slug": "mcp-assistant", "title": "MCP-Based Assistant", "objective": "Connect a client to a safe demo capability.", "level": "Advanced", "architecture": "host -> MCP client -> scoped server -> resource/tool", "steps": ["Expose a read-only lesson search", "Document arguments and output", "Review consent and trust boundaries"], "challenge": "Add a second resource without broadening permissions."},
	{"slug": "genai-capstone", "title": "Final GenAI Capstone", "objective": "Deliver a cited tutor with evaluation and operational checks.", "level": "Advanced", "architecture": "web UI -> Flask -> selective RAG -> model -> cited answer", "steps": ["Build ingestion and retrieval", "Add chat history and citations", "Evaluate quality, privacy and timeouts"], "challenge": "Demonstrate an unsupported question and a safe refusal."},
]


def get_chapters():
	return CHAPTERS


def get_chapter(slug):
	return next((chapter for chapter in CHAPTERS if chapter["slug"] == slug), None)


def build_chapter_tutor_context(slug, question=""):
	chapter = get_chapter(slug)
	if chapter is None:
		return ""
	question_terms = {term.strip(".,?!:;()[]{}\"'").lower() for term in question.split()}
	concepts = chapter["topics"]
	relevant = [
		concept for concept in concepts
		if any(term in concept.lower() or concept.lower() in term for term in question_terms if len(term) > 3)
	]
	selected = relevant[:4] or concepts[:4]
	return (
		f"Learning Hub chapter: {chapter['title']} ({chapter['level']}). "
		f"Current focus: {', '.join(selected)}. "
		f"Chapter explanation: {chapter['explanation'][:900]} "
		"Teach from this selected chapter when relevant; answer unrelated questions normally."
	)[:1600]